version: 2
sample:
  overwrite: true
  size: 200
visualization:
  order: visual
analyze.output.format: pdf
ensemble:
  size: 10
profiles:
  hadas:
    run:
      source: products/run-source/samples.json