ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :bangbang:
:important-caption: :exclamation:
:note-caption: :point_right:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

# Dummy Bank: Stateory

A sample test model for a queue scheduling application for a bank. The tested site is available at https://dummy-bank.provengo.tech.

## Basic concept: 
Model as state machine, one state per screen. Decide case parameters at each state.

## Files

link:spec/js/high-level.states.js[high-level.states.js]::
   Defines the high-level flows of the tests and connects them to the event-handlers.
   Uses Provengo's https://docs.provengo.tech/main/site/ProvengoCli/0.9.5/dsls/stateory.html[Stateory (State Machine) DSL ], and the https://docs.provengo.tech/main/site/ProvengoCli/0.9.5/libraries/constraints.html[Constraints library].
link:spec/js/handlers-automation.js[handlers-automation.js]::
    Defines Low-level handlers that perform control flow based on user decisions, and Selenium-based automation. 
    Uses Provengo's https://docs.provengo.tech/main/site/ProvengoCli/0.9.5/libraries/selenium.html[Selenium library].
link:meta-spec/book-writer.js[book-writer.js]::
    Code for generating manual test books from scenario files.
link:meta-spec/ranking.js[ranking.js]::
    Code for optimizing test suites.


## Things to try

IMPORTANT: These assume that you have provengo installed on your system. See https://docs.provengo.tech/main/site/ProvengoCli/0.9.5/installation.html[the install page on our documentation site] if not.


### Visualize the Spec

Draw the specification in a PDF file.

[code, bash]
----
$ provengo analyze -f pdf dummy-bank-stateory/
----

### Sample Runs from the Spec
Sample 5 scenarios into a file. The scenarios are stored in a file called `samples.json` (this can be changed using the `-o`/`--output-file` switch).

[code, bash]
----
$ provengo sample --size 5 dummy-bank-stateory/
----


### Visualize the Spec and the Suite
Draw the specification in a PDF file and highlight the sampled scenarios.

[code, bash]
----
$ provengo analyze -f pdf --highlight dummy-bank-stateory/products/run-source/samples.json dummy-bank-stateory
----

### Create an optimized test suite 

[code, bash]
----
$ provengo ensemble dummy-bank-stateory/
----

TIP:  The current link:./meta-spec/ranking.js#L22[RankingFunction] can hit a maximum of 8 targets. Therefore, the maximum rate is 8 as well. 
(You can change the link:./meta-spec/ranking.js#L11[GOALS array] to best fit to your test plan by adding or removing events).

TIP: If you didn't get the highest possible rank, you can try sampling again, or ask for a higher number of samples

[code, bash]
----
$ provengo sample --delete-previous --size 10 dummy-bank-stateory/
    
$ provengo ensemble dummy-bank-stateory/
----


### Generate a test-book 

create a manual test-book based on the ensemble results. 

[code, bash]
----
$ provengo gen-book -s dummy-bank-stateory/products/run-source/ensemble.json dummy-bank-stateory/
----











