version: 2
sample:
  overwrite: true
visualization:
  order: visual
  layout: horizontal
analyze:
  output:
    format: pdf
run:
  scripts:
    # before-test: config/hooks/start.sh
    # after-success: config/hooks/end.sh
    # after-failure: config/hooks/end.sh

